#!/usr/bin/env bash
DIRECTORY="/autograder/submission"

# Figure out which directory students put the code in:
[ -d "/autograder/submission/Code" ] && DIRECTORY="$DIRECTORY/Code"
[ -d "/autograder/submission/source" ] && DIRECTORY="$DIRECTORY/source"

# Copy submission code to source directory:
echo "Copying code to /autograder/source"
cp -v -R "$DIRECTORY/." /autograder/source

# Install the submission's dependencies:
pip3 install --user subprocess32 gradescope-utils flask gunicorn
pip3 install --user -r /autograder/source/requirements.txt

# Run tests and output results in JSON:
echo "Running autograder..."
python3 /autograder/source/run_tests.py
