#!/usr/bin/env bash
DIRECTORY="/autograder/submission"

# Figure out which directory students put the code in:
[ -d "/autograder/submission/Code" ] && DIRECTORY="$DIRECTORY/Code"
[ -d "/autograder/submission/source" ] && DIRECTORY="$DIRECTORY/source"

# Copy submission code to source directory:
echo "Copying code to /autograder/source"
cp -v -R "$DIRECTORY/." /autograder/source

# Run tests and output results in JSON:
echo "Running autograder..."
python3 /autograder/source/run_tests.py

# If you are debugging, the output will be found in
# the $SUBMISSION_DIR/results directory defned in debug.sh:
cp -r /autograder/results /autograder/submission/results
